/**
 * Core type definitions for the Amor inteligente AI Engine SMART Action system.
 *
 * SMARTAction is the primary output schema. All model outputs must conform
 * to this structure and pass SMART validation before being surfaced to users.
 */

// ---------------------------------------------------------------------------
// SMART Action output schema
// ---------------------------------------------------------------------------

/** A single SMART action generated by the planner. */
export interface SMARTAction {
  /** Concrete, specific action description with a verb + artefact. */
  action: string;
  /** How success will be measured (numeric target or countable outcome). */
  metric: string;
  /** Current starting point or baseline for the metric. */
  baseline: string;
  /** Target value or outcome to reach. */
  target: string;
  /** ISO 8601 date string or human-readable deadline (e.g. "2025-02-14"). */
  deadline: string;
  /** Why this action matters for the stated goal. */
  rationale: string;
  /** Estimated effort (e.g. "2 hours/week", "30 minutes one-off"). */
  effort_estimate: string;
  /** The very first concrete step to take. */
  first_step: string;
  /** Optional: ID of the retrieval-pack template that grounded this action. */
  template_id?: string;
}

/** Complete plan output from the planner. */
export interface SMARTPlan {
  actions: SMARTAction[];
  /** Model and retrieval metadata for traceability. */
  metadata: PlanMetadata;
}

export interface PlanMetadata {
  model_id: string;
  model_version: string;
  backend: InferenceBackend;
  retrieval_pack_version: string;
  generated_at: string;
  generation_time_ms: number;
  tokens_generated: number;
}

// ---------------------------------------------------------------------------
// User profile (input to the planner)
// ---------------------------------------------------------------------------

/** Structured barrier metadata resolved from the barrier catalog. */
export interface ResolvedBarrier {
  /** Canonical barrier ID. */
  id: string;
  /** Human-readable label. */
  label: string;
  /** Broad barrier category for routing. */
  category: string;
  /** Tags to boost retrieval matching. */
  retrieval_tags: string[];
  /** Guidance hints to inject into the prompt. */
  prompt_hints: string[];
  /** Assumptions the model must NOT make. */
  do_not_assume: string[];
  /** Job-search stages to deprioritise. */
  contraindicated_stages: string[];
}

/** Normalised user profile used by the prompt assembler. */
export interface UserProfile {
  /** The user's target job or career goal. */
  job_goal: string;
  /** Current situation summary (e.g. "unemployed", "career changer from retail"). */
  current_situation: string;
  /** Available hours per week for job-search activities. */
  hours_per_week: number;
  /** Target timeframe in weeks (e.g. 8 for "within 8 weeks"). */
  timeframe_weeks: number;
  /** Known skills and experience. */
  skills: string[];
  /** Barriers or constraints (e.g. "childcare", "disability affecting stamina"). */
  barriers: string[];
  /** Confidence level (1-5, where 1 = very anxious, 5 = highly confident). */
  confidence_level: number;
  /** Industry or sector of interest. */
  industry?: string;
  /** Preferred work arrangement. */
  work_arrangement?: "any" | "remote" | "hybrid" | "on-site";
  /** Participant's first name (for personalising actions). */
  participant_name: string;
  /** Who supports the action (e.g. "Advisor", participant name). */
  supporter: string;
  /** Structured barrier metadata resolved from the barrier catalog (if available). */
  resolved_barrier?: ResolvedBarrier;
}

/** Raw user input before normalisation. */
export interface RawUserInput {
  goal: string;
  situation?: string;
  hours_per_week?: number;
  timeframe?: string;
  skills?: string;
  barriers?: string;
  confidence?: string;
  industry?: string;
  work_arrangement?: string;
  /** Participant's first name. */
  participant_name?: string;
  /** Who supports the action (e.g. "Advisor", participant name). */
  supporter?: string;
  /** Canonical barrier ID from the barrier catalog (deterministic, bypasses keyword parsing). */
  selected_barrier_id?: string;
  /** Human-readable barrier label as shown in the UI dropdown. */
  selected_barrier_label?: string;
}

// ---------------------------------------------------------------------------
// Retrieval / knowledge pack
// ---------------------------------------------------------------------------

/** A curated action template from the retrieval pack. */
export interface ActionTemplate {
  id: string;
  /** Job-search stage this template belongs to. */
  stage: JobSearchStage;
  /** Template action text with optional placeholders ({goal}, {skill}, etc). */
  action_template: string;
  /** Default metric template. */
  metric_template: string;
  /** Suggested effort estimate. */
  effort_hint: string;
  /** Tags for retrieval matching. */
  tags: string[];
  /** Barrier types this template is especially relevant for. */
  relevant_barriers: string[];
  /** Minimum confidence level where this template is appropriate (1-5). */
  min_confidence: number;
  /** Source attribution (e.g. "National Careers Service, OGL v3.0"). */
  source_attribution: string;
}

export type JobSearchStage =
  | "discovery"
  | "cv_preparation"
  | "online_presence"
  | "applications"
  | "networking"
  | "upskilling"
  | "interviewing"
  | "follow_up";

/** A skills/occupation entry from the taxonomy pack. */
export interface SkillEntry {
  id: string;
  label: string;
  /** Broader category (e.g. "Digital skills", "Communication"). */
  category: string;
  /** Related occupation families. */
  occupations: string[];
  source: "onet" | "esco" | "ncs" | "custom";
}

/** Retrieval pack manifest. */
export interface RetrievalPack {
  version: string;
  updated_at: string;
  templates: ActionTemplate[];
  skills: SkillEntry[];
}

// ---------------------------------------------------------------------------
// Inference runtime
// ---------------------------------------------------------------------------

export type InferenceBackend = "webgpu" | "wasm-simd" | "wasm-basic";

/** Capabilities detected for the current browser environment. */
export interface BrowserCapabilities {
  webgpu: boolean;
  wasmSimd: boolean;
  wasmThreads: boolean;
  crossOriginIsolated: boolean;
  /** Estimated available memory in MB (best-effort, may be undefined). */
  estimatedMemoryMB?: number;
}

/** Configuration for the inference engine. */
export interface InferenceConfig {
  /** Model identifier (e.g. "smart-planner-150m-q4"). */
  model_id: string;
  /** Base URL for fetching model files. */
  model_base_url: string;
  /** Preferred backend (auto-detected if not specified). */
  preferred_backend?: InferenceBackend;
  /** Maximum sequence length for generation. */
  max_seq_length: number;
  /** Maximum new tokens to generate per request. */
  max_new_tokens: number;
  /** Temperature for sampling (0 = greedy/deterministic). */
  temperature: number;
  /** Top-p nucleus sampling threshold. */
  top_p: number;
  /** Repetition penalty (1.0 = no penalty). */
  repetition_penalty: number;
}

/** Model file manifest for chunked loading. */
export interface ModelManifest {
  model_id: string;
  version: string;
  format: "onnx" | "gguf";
  /** Total size in bytes across all files. */
  total_bytes: number;
  files: ModelFile[];
  tokenizer_file: string;
  config_file: string;
}

export interface ModelFile {
  filename: string;
  size_bytes: number;
  sha256: string;
  /** Whether this file is required for initial inference (vs. lazy-loaded). */
  required: boolean;
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/** Result of SMART validation for a single action. */
export interface ValidationResult {
  valid: boolean;
  criteria: SMARTCriteriaResult;
  /** Overall score 0-100. */
  score: number;
  /** Human-readable issues found. */
  issues: string[];
  /** Suggestions for improvement. */
  suggestions: string[];
}

export interface SMARTCriteriaResult {
  specific: CriterionResult;
  measurable: CriterionResult;
  achievable: CriterionResult;
  relevant: CriterionResult;
  time_bound: CriterionResult;
}

export interface CriterionResult {
  passed: boolean;
  score: number;
  reason: string;
}

// ---------------------------------------------------------------------------
// Delivery / caching
// ---------------------------------------------------------------------------

export interface CacheEntry {
  url: string;
  etag?: string;
  cached_at: number;
  size_bytes: number;
  version: string;
}

export interface DownloadProgress {
  file: string;
  loaded_bytes: number;
  total_bytes: number;
  phase: "downloading" | "caching" | "complete" | "error";
  error?: string;
}

/** Messages sent between the main thread and the inference worker. */
export type WorkerMessage =
  | { type: "init"; config: InferenceConfig }
  | { type: "init_complete"; backend: InferenceBackend }
  | { type: "init_error"; error: string }
  | { type: "generate"; id: string; prompt: string; config: Partial<InferenceConfig> }
  | { type: "token"; id: string; token: string; done: boolean }
  | { type: "generate_complete"; id: string; text: string; tokens_generated: number; time_ms: number }
  | { type: "generate_error"; id: string; error: string }
  | { type: "progress"; progress: DownloadProgress }
  | { type: "abort"; id: string };
